<<<<<<< HEAD
name: proyecto_fitchain_establecimiento
=======
name: proyecto_fitchain
>>>>>>> pÂc
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar y obtener codigo
        uses: actions/checkout@v4

      - name: Crear carpeta en AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.IP_SERVER}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
<<<<<<< HEAD
            mkdir -p /home/ubuntu/java/Establecimiento

      - name: Sincronizar proyecto en el servidor
        uses: burnett01/rsync-deployments@v8
        with:
          switches: "-avz --delete"
          path: "./"
=======
                  mkdir -p /home/ubuntu/java/Establecimiento

      - name : Sincronizar proyecto en el servidor
        uses: burnett01/rsync-deployments@v8
        with:
          switches: "-avz --delete"
          path: './'
>>>>>>> pÂc
          remote_host: ${{secrets.IP_SERVER}}
          remote_user: ${{secrets.USERNAME}}
          remote_path: "/home/ubuntu/java/Establecimiento"
          remote_key: ${{secrets.KEY}}
          remote_port: ${{secrets.PORT}}

<<<<<<< HEAD
=======

>>>>>>> pÂc
      - name: Levantar docker con docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.IP_SERVER}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
<<<<<<< HEAD
            cd /home/ubuntu/java/
            docker compose up -d --build establecimiento
=======
                  cd /home/ubuntu/java/
                  docker compose down
                  docker compose up -d --build
>>>>>>> pÂc
